AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ExpressLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs20.x
      CodeUri: .
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          NODE_ENV: development
          DB_NAME: technical_test
          DB_USER: admin
          DB_PASSWORD: wX{KG3f*Y(KDfNWeQH6#d?Wq:G3(
          DB_HOST: database-1.cluster-cjka26ime9ff.us-east-1.rds.amazonaws.com
          DB_PORT: 3306
          GOOGLE_API_KEY: AIzaSyDw0ITnWNGe8H8Xp3bx4yU6gzlOJYz9XB8
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiGatewayUrl:
    Description: URL para acceder a la API
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
